apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: education-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/education-platform.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10

